---
title: "Connectivity Analyses"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## EU-AIMS ADI-R Subtyping Connectivity Analysis


```{r, warning=FALSE, message=FALSE}
easypackages::libraries(c("here","ggplot2","nlme","readxl","matlabr","circlize","scico"))
source("/Users/mlombardo/Dropbox/GitHubRepos/utils/cohens_d.R")
source("/Users/mlombardo/Dropbox/R/Repfunctionspack6.R")
source("/Users/mlombardo/Dropbox/R/get_ggColorHue.R")
fdr_thresh = 0.05

z_thresh = 0.8

options(matlab.path = "/Applications/MATLAB_R2019b.app/bin")

rootpath = "/Users/mlombardo/Dropbox/euaims/data/adir"
datapath = here("data")
codepath = here("code")
resultpath = here("results")
plotpath = here("plots")

```

## Run the MATLAB script that estimates the partial correlations 
```{r, warning=FALSE, message=FALSE}
RUNMATLAB = TRUE

if (RUNMATLAB){
  code2run = sprintf("cd %s; estimateConnectivity_z08('%s',0,1);",codepath,"ridge")
  res = run_matlab_code(code2run)
}
```


```{r, warning=FALSE, message=FALSE}
fname = sprintf("partialCorData_ridge_lambda1.diffzscoreGrps_z%s.txt",as.character(z_thresh))

fname2open = file.path(datapath, fname)
df = read.delim(fname2open)
df = subset(df,df$subgrp!="RRB_over_SC")

tmp_df = read.csv(file.path(datapath,sprintf("tidy_euaims_NDAR_subtypes_diffscore_z%s.csv",as.character(z_thresh))))
tmp_df = subset(tmp_df,tmp_df$svm_pred_labels!="RRB_over_SC")
tmp_df$A_pct_severity = (tmp_df$A1_pct_severity+tmp_df$A2_pct_severity+tmp_df$A3_pct_severity)/3
tmp_df$B_pct_severity = (tmp_df$B1_pct_severity+tmp_df$B2_pct_severity+tmp_df$B3_pct_severity+tmp_df$B4_pct_severity)/4

asd_df = merge(tmp_df[,c("subid","A1_pct_severity","A2_pct_severity","A3_pct_severity",
                        "B1_pct_severity","B2_pct_severity","B3_pct_severity","B4_pct_severity",
                        "A_pct_severity","B_pct_severity","z_ds")],
           df,
           by="subid")
```



```{r, warning=FALSE, message=FALSE}
RUNANALYSIS = TRUE

if (RUNANALYSIS==TRUE) {
  
  # columns with connectivity data
  vars2use = colnames(df)[10:ncol(df)]
  
  cnames = c("compNames",
             "SCequalRRB_Disc_vs_TD.tstat","SCequalRRB_Disc_vs_TD.pval", 
             "SCequalRRB_Disc_vs_TD.es","SCequalRRB_Disc_vs_TD.AIC","SCequalRRB_Disc_vs_TD.BIC",
             "SCequalRRB_Rep_vs_TD.tstat","SCequalRRB_Rep_vs_TD.pval","SCequalRRB_Rep_vs_TD.es", 
             "SCequalRRB_Rep_vs_TD.AIC","SCequalRRB_Rep_vs_TD.BIC", "SCequalRRB.repBF",
             "SCoverRRB_Disc_vs_TD.tstat","SCoverRRB_Disc_vs_TD.pval", 
             "SCoverRRB_Disc_vs_TD.es","SCoverRRB_Disc_vs_TD.AIC","SCoverRRB_Disc_vs_TD.BIC",
             "SCoverRRB_Rep_vs_TD.tstat","SCoverRRB_Rep_vs_TD.pval","SCoverRRB_Rep_vs_TD.es",
             "SCoverRRB_Rep_vs_TD.AIC","SCoverRRB_Rep_vs_TD.BIC", "SCoverRRB.repBF",
             "SCequalRRB_Disc_vs_SCoverRRB.tstat","SCequalRRB_Disc_vs_SCoverRRB.pval",
             "SCequalRRB_Disc_vs_SCoverRRB.es","SCequalRRB_Disc_vs_SCoverRRB.AIC","SCequalRRB_Disc_vs_SCoverRRB.BIC",
             "SCequalRRB_Rep_vs_SCoverRRB.tstat","SCequalRRB_Rep_vs_SCoverRRB.pval","SCequalRRB_Rep_vs_SCoverRRB.es",
             "SCequalRRB_Rep_vs_SCoverRRB.AIC","SCequalRRB_Rep_vs_SCoverRRB.BIC","SCequalRRB_vs_SCoverRRB.repBF")
  
  aovres = data.frame(matrix(nrow = length(vars2use),ncol = length(cnames)))
  colnames(aovres) = cnames
  rownames(aovres) = vars2use
  aovres$compNames = vars2use
  vars2loop = c(1:length(vars2use))

  for (i in vars2loop) {
  	y_var = vars2use[i]

    # run analyses on Discovery and Replication datasets
  	df_Disc = subset(df, df$dataset=="Discovery")
    df_Rep = subset(df, df$dataset=="Replication")

  	# grab residuals after accounting for sex and scan_age
  	fx_form2 = as.formula(sprintf("%s ~ %s + %s",y_var,"sex","scan_age"))
  	rx_form = as.formula(sprintf("~ 1|%s","site"))
  	mod2use = eval(substitute(lme(fixed = fx_form2,
  	                              random = rx_form,
  	                              data = df_Disc,
  	                              na.action = na.omit)))
    df_Disc$data2plot = resid(mod2use)
  
    # compute t-stats
    fx_form = as.formula(sprintf("%s ~ %s + %s + %s",y_var,"subgrp","sex","scan_age"))
  	rx_form = as.formula(sprintf("~ 1|%s","site"))
  	
  	DASD1 = subset(df_Disc, df_Disc$subgrp=="SC_equal_RRB" | df_Disc$subgrp=="TD")
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = DASD1, 
  	                              na.action = na.omit)))
    res = summary(mod2use)
    SCequalRRB_vs_TD_Disc_statistic = res$tTable[2,4]
    SCequalRRB_vs_TD_Disc_p.value = res$tTable[2,5]
    SCequalRRB_vs_TD_Disc.AIC = AIC(mod2use)
    SCequalRRB_vs_TD_Disc.BIC = BIC(mod2use)
    
  	DASD2 = subset(df_Disc, df_Disc$subgrp=="SC_over_RRB" | df_Disc$subgrp=="TD")
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = DASD2, 
  	                              na.action = na.omit)))
    res = summary(mod2use)
    SCoverRRB_vs_TD_Disc_statistic = res$tTable[2,4]
    SCoverRRB_vs_TD_Disc_p.value = res$tTable[2,5]
    SCoverRRB_vs_TD_Disc.AIC = AIC(mod2use)
    SCoverRRB_vs_TD_Disc.BIC = BIC(mod2use)

  # 	DASD3 = subset(df_Disc, df_Disc$subgrp=="RRB_over_SC" | df_Disc$subgrp=="TD")
  # 	mod2use = eval(substitute(lme(fixed = fx_form, 
  # 	                              random = rx_form, 
  # 	                              data = DASD3, 
  # 	                              na.action = na.omit)))
  #   res = summary(mod2use)
  #   RRBoverSC_vs_TD_Disc_statistic = res$tTable[2,4]
  #   RRBoverSC_vs_TD_Disc_p.value = res$tTable[2,5]
  #   RRBoverSC_vs_TD_Disc.AIC = AIC(mod2use)
  #   RRBoverSC_vs_TD_Disc.BIC = BIC(mod2use)
    
    DASD4 = subset(df_Disc, df_Disc$subgrp=="SC_equal_RRB" | df_Disc$subgrp=="SC_over_RRB")
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = DASD4, 
  	                              na.action = na.omit)))
    res = summary(mod2use)
    SCequalRRB_vs_SCoverRRB_Disc_statistic = res$tTable[2,4]
    SCequalRRB_vs_SCoverRRB_Disc_p.value = res$tTable[2,5]
    SCequalRRB_vs_SCoverRRB_Disc.AIC = AIC(mod2use)
    SCequalRRB_vs_SCoverRRB_Disc.BIC = BIC(mod2use)
    
    aovres[y_var,"SCequalRRB_Disc_vs_TD.tstat"] = SCequalRRB_vs_TD_Disc_statistic
    aovres[y_var,"SCequalRRB_Disc_vs_TD.pval"] = SCequalRRB_vs_TD_Disc_p.value
    aovres[y_var,"SCequalRRB_Disc_vs_TD.es"] = cohens_d(df_Disc$data2plot[df_Disc$subgrp=="SC_equal_RRB"],
                                             df_Disc$data2plot[df_Disc$subgrp=="TD"])
    aovres[y_var,"SCequalRRB_Disc_vs_TD.AIC"] = SCequalRRB_vs_TD_Disc.AIC
    aovres[y_var,"SCequalRRB_Disc_vs_TD.BIC"] = SCequalRRB_vs_TD_Disc.BIC

    aovres[y_var,"SCoverRRB_Disc_vs_TD.tstat"] = SCoverRRB_vs_TD_Disc_statistic
    aovres[y_var,"SCoverRRB_Disc_vs_TD.pval"] = SCoverRRB_vs_TD_Disc_p.value
    aovres[y_var,"SCoverRRB_Disc_vs_TD.es"] = cohens_d(df_Disc$data2plot[df_Disc$subgrp=="SC_over_RRB"],
                                             df_Disc$data2plot[df_Disc$subgrp=="TD"])
    aovres[y_var,"SCoverRRB_Disc_vs_TD.AIC"] = SCoverRRB_vs_TD_Disc.AIC
    aovres[y_var,"SCoverRRB_Disc_vs_TD.BIC"] = SCoverRRB_vs_TD_Disc.BIC

    # aovres[y_var,"RRBoverSC_Disc_vs_TD.tstat"] = RRBoverSC_vs_TD_Disc_statistic
    # aovres[y_var,"RRBoverSC_Disc_vs_TD.pval"] = RRBoverSC_vs_TD_Disc_p.value
    # aovres[y_var,"RRBoverSC_Disc_vs_TD.es"] = cohens_d(df_Disc$data2plot[df_Disc$subgrp=="RRB_over_SC"],
    #                                          df_Disc$data2plot[df_Disc$subgrp=="TD"])
    # aovres[y_var,"RRBoverSC_Disc_vs_TD.AIC"] = RRBoverSC_vs_TD_Disc.AIC
    # aovres[y_var,"RRBoverSC_Disc_vs_TD.BIC"] = RRBoverSC_vs_TD_Disc.BIC
    
    aovres[y_var,"SCequalRRB_Disc_vs_SCoverRRB.tstat"] = SCequalRRB_vs_SCoverRRB_Disc_statistic
    aovres[y_var,"SCequalRRB_Disc_vs_SCoverRRB.pval"] = SCequalRRB_vs_SCoverRRB_Disc_p.value
    aovres[y_var,"SCequalRRB_Disc_vs_SCoverRRB.es"] = cohens_d(df_Disc$data2plot[df_Disc$subgrp=="SC_equal_RRB"],
                                             df_Disc$data2plot[df_Disc$subgrp=="SC_over_RRB"])
    aovres[y_var,"SCequalRRB_Disc_vs_SCoverRRB.AIC"] = SCequalRRB_vs_SCoverRRB_Disc.AIC
    aovres[y_var,"SCequalRRB_Disc_vs_SCoverRRB.BIC"] = SCequalRRB_vs_SCoverRRB_Disc.BIC

    
    # Replication

  	# grab residuals after accounting for sex and scan_age
  	fx_form2 = as.formula(sprintf("%s ~ %s + %s",y_var,"sex","scan_age"))
  	mod2use = eval(substitute(lme(fixed = fx_form2,
  	                              random = rx_form,
  	                              data = df_Rep,
  	                              na.action = na.omit)))
    df_Rep$data2plot = resid(mod2use)

    # compute t-stats
    fx_form = as.formula(sprintf("%s ~ %s + %s + %s",y_var,"subgrp","sex","scan_age"))
  	rx_form = as.formula(sprintf("~ 1|%s","site"))
  	
  	DASD1 = subset(df_Rep, df_Rep$subgrp=="SC_equal_RRB" | df_Rep$subgrp=="TD")
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = DASD1, 
  	                              na.action = na.omit)))
    res = summary(mod2use)
    SCequalRRB_vs_TD_Rep_statistic = res$tTable[2,4]
    SCequalRRB_vs_TD_Rep_p.value = res$tTable[2,5]
    SCequalRRB_vs_TD_Rep.AIC = AIC(mod2use)
    SCequalRRB_vs_TD_Rep.BIC = BIC(mod2use)

  	DASD2 = subset(df_Rep, df_Rep$subgrp=="SC_over_RRB" | df_Rep$subgrp=="TD")
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = DASD2, 
  	                              na.action = na.omit)))
    res = summary(mod2use)
    SCoverRRB_vs_TD_Rep_statistic = res$tTable[2,4]
    SCoverRRB_vs_TD_Rep_p.value = res$tTable[2,5]
    SCoverRRB_vs_TD_Rep.AIC = AIC(mod2use)
    SCoverRRB_vs_TD_Rep.BIC = BIC(mod2use)

  # 	DASD3 = subset(df_Rep, df_Rep$subgrp=="RRB_over_SC" | df_Rep$subgrp=="TD")
  # 	mod2use = eval(substitute(lme(fixed = fx_form, 
  # 	                              random = rx_form, 
  # 	                              data = DASD3, 
  # 	                              na.action = na.omit)))
  #   res = summary(mod2use)
  #   RRBoverSC_vs_TD_Rep_statistic = res$tTable[2,4]
  #   RRBoverSC_vs_TD_Rep_p.value = res$tTable[2,5]
  #   RRBoverSC_vs_TD_Rep.AIC = AIC(mod2use)
  #   RRBoverSC_vs_TD_Rep.BIC = BIC(mod2use)
    
    DASD4 = subset(df_Rep, df_Rep$subgrp=="SC_equal_RRB" | df_Rep$subgrp=="SC_over_RRB")
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = DASD4, 
  	                              na.action = na.omit)))
    res = summary(mod2use)
    SCequalRRB_vs_SCoverRRB_Rep_statistic = res$tTable[2,4]
    SCequalRRB_vs_SCoverRRB_Rep_p.value = res$tTable[2,5]
    SCequalRRB_vs_SCoverRRB_Rep.AIC = AIC(mod2use)
    SCequalRRB_vs_SCoverRRB_Rep.BIC = BIC(mod2use)

    aovres[y_var,"SCequalRRB_Rep_vs_TD.tstat"] = SCequalRRB_vs_TD_Rep_statistic
    aovres[y_var,"SCequalRRB_Rep_vs_TD.pval"] = SCequalRRB_vs_TD_Rep_p.value
    aovres[y_var,"SCequalRRB_Rep_vs_TD.es"] = cohens_d(df_Rep$data2plot[df_Rep$subgrp=="SC_equal_RRB"],
                                            df_Rep$data2plot[df_Rep$subgrp=="TD"])
    aovres[y_var,"SCequalRRB_Rep_vs_TD.AIC"] = SCequalRRB_vs_TD_Rep.AIC
    aovres[y_var,"SCequalRRB_Rep_vs_TD.BIC"] = SCequalRRB_vs_TD_Rep.BIC

    aovres[y_var,"SCoverRRB_Rep_vs_TD.tstat"] = SCoverRRB_vs_TD_Rep_statistic
    aovres[y_var,"SCoverRRB_Rep_vs_TD.pval"] = SCoverRRB_vs_TD_Rep_p.value
    aovres[y_var,"SCoverRRB_Rep_vs_TD.es"] = cohens_d(df_Rep$data2plot[df_Rep$subgrp=="SC_over_RRB"],
                                            df_Rep$data2plot[df_Rep$subgrp=="TD"])
    aovres[y_var,"SCoverRRB_Rep_vs_TD.AIC"] = SCoverRRB_vs_TD_Rep.AIC
    aovres[y_var,"SCoverRRB_Rep_vs_TD.BIC"] = SCoverRRB_vs_TD_Rep.BIC

    # aovres[y_var,"RRBoverSC_Rep_vs_TD.tstat"] = RRBoverSC_vs_TD_Rep_statistic
    # aovres[y_var,"RRBoverSC_Rep_vs_TD.pval"] = RRBoverSC_vs_TD_Rep_p.value
    # aovres[y_var,"RRBoverSC_Rep_vs_TD.es"] = cohens_d(df_Rep$data2plot[df_Rep$subgrp=="RRB_over_SC"],
    #                                         df_Rep$data2plot[df_Rep$subgrp=="TD"])
    # aovres[y_var,"RRBoverSC_Rep_vs_TD.AIC"] = RRBoverSC_vs_TD_Rep.AIC
    # aovres[y_var,"RRBoverSC_Rep_vs_TD.BIC"] = RRBoverSC_vs_TD_Rep.BIC
    
    aovres[y_var,"SCequalRRB_Rep_vs_SCoverRRB.tstat"] = SCequalRRB_vs_SCoverRRB_Rep_statistic
    aovres[y_var,"SCequalRRB_Rep_vs_SCoverRRB.pval"] = SCequalRRB_vs_SCoverRRB_Rep_p.value
    aovres[y_var,"SCequalRRB_Rep_vs_SCoverRRB.es"] = cohens_d(df_Rep$data2plot[df_Rep$subgrp=="SC_equal_RRB"],
                                             df_Rep$data2plot[df_Rep$subgrp=="SC_over_RRB"])
    aovres[y_var,"SCequalRRB_Rep_vs_SCoverRRB.AIC"] = SCequalRRB_vs_SCoverRRB_Rep.AIC
    aovres[y_var,"SCequalRRB_Rep_vs_SCoverRRB.BIC"] = SCequalRRB_vs_SCoverRRB_Rep.BIC

    current_state = sprintf("Loop %d",i)
    fname2save = file.path(resultpath,"anova_allconnections","monitor.csv")
  write.table(current_state, file = fname2save, sep = ",", quote = FALSE, col.names = NA)
  
    res_bf = BFSALL(tobs = SCequalRRB_vs_TD_Disc_statistic, 
                      trep = SCequalRRB_vs_TD_Rep_statistic, 
                      n1 = sum(df_Disc$subgrp=="SC_equal_RRB"), 
                      n2 = sum(df_Rep$subgrp=="SC_equal_RRB"),
                      m1 = sum(df_Disc$subgrp=="TD"), 
                      m2 = sum(df_Rep$subgrp=="TD"),
                      sample = 2, 
                      Type = 'ALL')
    aovres[y_var,"SCequalRRB.repBF"] = res_bf[4,2]
  
    res_bf = BFSALL(tobs = SCoverRRB_vs_TD_Disc_statistic, 
                    trep = SCoverRRB_vs_TD_Rep_statistic,
                    n1 = sum(df_Disc$subgrp=="SC_over_RRB"), 
                    n2 = sum(df_Rep$subgrp=="SC_over_RRB"),
                    m1 = sum(df_Disc$subgrp=="TD"), 
                    m2 = sum(df_Rep$subgrp=="TD"),
                    sample = 2, 
                    Type = 'ALL')
    aovres[y_var,"SCoverRRB.repBF"] = res_bf[4,2]
  
    # # print("RRBoverSC")
    # res_bf = BFSALL(tobs = RRBoverSC_vs_TD_Disc_statistic, 
    #                 trep = RRBoverSC_vs_TD_Rep_statistic, 
    #                 n1 = sum(df_Disc$subgrp=="RRB_over_SC"), 
    #                 n2 = sum(df_Rep$subgrp=="RRB_over_SC"),
    #                 m1 = sum(df_Disc$subgrp=="TD"), 
    #                 m2 = sum(df_Rep$subgrp=="TD"),
    #                 sample = 2,
    #                 Type = 'ALL')
    # aovres[y_var,"RRBoverSC.repBF"] = res_bf[4,2]
    
    res_bf = BFSALL(tobs = SCequalRRB_vs_SCoverRRB_Disc_statistic, 
                      trep = SCequalRRB_vs_SCoverRRB_Rep_statistic, 
                      n1 = sum(df_Disc$subgrp=="SC_equal_RRB"), 
                      n2 = sum(df_Rep$subgrp=="SC_equal_RRB"),
                      m1 = sum(df_Disc$subgrp=="SC_over_RRB"), 
                      m2 = sum(df_Rep$subgrp=="SC_over_RRB"),
                      sample = 2, 
                      Type = 'ALL')
    aovres[y_var,"SCequalRRB_vs_SCoverRRB.repBF"] = res_bf[4,2]

    # save results to a file
    fname2save = file.path(resultpath,"anova_allconnections",sprintf("partialCor_ALLsubs_ridge1_lme_fx_subgrp_sex_scan_age_rx_site_diffzscoreGrps_z%s.csv",as.character(z_thresh)))
    write.table(aovres, file = fname2save, sep = ",", quote = FALSE, col.names = NA)

  }
  
  mask1 = aovres$SCequalRRB.repBF>=10
  mask2 = aovres$SCoverRRB.repBF>=10
  # mask3 = aovres$RRBoverSC.repBF>=10
  mask4 = aovres$SCequalRRB_vs_SCoverRRB.repBF>=10
  mask_allBF = mask1 | mask2 | mask4
  print(aovres[mask_allBF,])
  
  # save results to a file
  fname2save = file.path(resultpath,"anova_allconnections",sprintf("partialCor_ALLsubs_ridge1_lme_fx_subgrp_sex_scan_age_rx_site_diffzscoreGrps_z%s.csv",as.character(z_thresh)))
  write.table(aovres, file = fname2save, sep = ",", quote = FALSE, col.names = NA)

} else {
  
  fname = file.path(resultpath,"anova_allconnections",sprintf("partialCor_ALLsubs_ridge1_lme_fx_subgrp_sex_scan_age_rx_site_z%s.xlsx",as.character(z_thresh)))
  aovres = read_excel(fname)
}

mask1 = aovres$SCequalRRB.repBF>=10
mask2 = aovres$SCoverRRB.repBF>=10
# mask3 = aovres$RRBoverSC.repBF>=10
mask4 = aovres$SCequalRRB_vs_SCoverRRB.repBF>=10
mask_allBF = mask1 | mask2 | mask4 

aovres[mask_allBF,c("compNames","SCequalRRB.repBF","SCoverRRB.repBF")]
```

## Chord diagram

```{r, warning=FALSE, message=FALSE}
ncomp_pairs = dim(aovres)[1]
comps = c("IC01","IC03","IC04","IC05","IC06","IC07","IC08","IC09","IC10","IC11","IC12","IC13","IC14","IC15","IC16","IC17","IC18","IC19","IC20")
ncomps = length(comps)

SCequalRRB_Disc_mat = matrix(nrow = ncomps, ncol = ncomps)
rownames(SCequalRRB_Disc_mat) = comps
colnames(SCequalRRB_Disc_mat) = comps
diag(SCequalRRB_Disc_mat) = 0

SCequalRRB_Rep_mat = matrix(nrow = ncomps, ncol = ncomps)
rownames(SCequalRRB_Rep_mat) = comps
colnames(SCequalRRB_Rep_mat) = comps
diag(SCequalRRB_Rep_mat) = 0

SCoverRRB_Disc_mat = matrix(nrow = ncomps, ncol = ncomps)
rownames(SCoverRRB_Disc_mat) = comps
colnames(SCoverRRB_Disc_mat) = comps
diag(SCoverRRB_Disc_mat) = 0

SCoverRRB_Rep_mat = matrix(nrow = ncomps, ncol = ncomps)
rownames(SCoverRRB_Rep_mat) = comps
colnames(SCoverRRB_Rep_mat) = comps
diag(SCoverRRB_Rep_mat) = 0

for (comp_pair in aovres$compNames){
  comp1 = substr(comp_pair,1,4)
  comp2 = substr(comp_pair,6,10)
  
  if (aovres[comp_pair,"SCequalRRB.repBF"]>10 & 
      aovres[comp_pair,"SCequalRRB_Disc_vs_TD.pval"]<0.05 & 
      aovres[comp_pair,"SCequalRRB_Rep_vs_TD.pval"]<0.05){
    SCequalRRB_Disc_mat[comp1,comp2] = aovres[comp_pair,"SCequalRRB_Disc_vs_TD.es"]
    SCequalRRB_Rep_mat[comp1,comp2] = aovres[comp_pair,"SCequalRRB_Rep_vs_TD.es"]
  } else{
    SCequalRRB_Disc_mat[comp1,comp2] = 0.0001
    SCequalRRB_Rep_mat[comp1,comp2] = 0.0001
  }
  
  if (aovres[comp_pair,"SCoverRRB.repBF"]>10 & 
      aovres[comp_pair,"SCoverRRB_Disc_vs_TD.pval"]<0.05 & 
      aovres[comp_pair,"SCoverRRB_Rep_vs_TD.pval"]<0.05){
    SCoverRRB_Disc_mat[comp1,comp2] = aovres[comp_pair,"SCoverRRB_Disc_vs_TD.es"]
    SCoverRRB_Rep_mat[comp1,comp2] = aovres[comp_pair,"SCoverRRB_Rep_vs_TD.es"]
  } else{
    SCoverRRB_Disc_mat[comp1,comp2] = 0.0001
    SCoverRRB_Rep_mat[comp1,comp2] = 0.0001
  }
  
}

grid.col = c(IC01 = "grey",
             IC03 = "grey",
             IC04 = "grey",
             IC05 = "grey",
             IC06 = "grey",
             IC07 = "grey", 
             IC08 = "grey",
             IC09 = "grey",
             IC10 = "grey",
             IC11 = "grey",
             IC12 = "grey",
             IC13 = "grey", 
             IC14 = "grey",
             IC15 = "grey",
             IC16 = "grey",
             IC17 = "grey",
             IC18 = "grey",
             IC19 = "grey",
             IC20 = "grey")


col_fun = colorRamp2(c(-0.5, 0, 0.5), c("blue", "white", "red"))
circos.clear()
circos.par(gap.after = c(rep(10, ncomps)))
chordDiagram(SCequalRRB_Disc_mat, grid.col = grid.col, col=col_fun, annotationTrack = c("name","grid"))

col_fun = colorRamp2(c(-0.5, 0, 0.5), c("blue", "white", "red"))
circos.clear()
circos.par(gap.after = c(rep(10, ncomps)))
chordDiagram(SCequalRRB_Rep_mat, grid.col = grid.col, col=col_fun, annotationTrack = c("name","grid"))




grid.col = c(IC01 = "grey",
             IC03 = "grey",
             IC04 = "grey",
             IC05 = "grey",
             IC06 = "grey",
             IC07 = "grey", 
             IC08 = "grey",
             IC09 = "grey",
             IC10 = "grey",
             IC11 = "grey",
             IC12 = "grey",
             IC13 = "grey", 
             IC14 = "grey",
             IC15 = "grey",
             IC16 = "grey",
             IC17 = "grey",
             IC18 = "grey",
             IC19 = "grey",
             IC20 = "grey")

col_fun = colorRamp2(c(-0.5, 0, 0.5), c("blue", "white", "red"))
circos.clear()
circos.par(gap.after = c(rep(10, ncomps)))
chordDiagram(SCoverRRB_Disc_mat, grid.col = grid.col, col=col_fun, annotationTrack = c("name","grid"))

col_fun = colorRamp2(c(-0.5, 0, 0.5), c("blue", "white", "red"))
circos.clear()
circos.par(gap.after = c(rep(10, ncomps)))
chordDiagram(SCoverRRB_Rep_mat, grid.col = grid.col, col=col_fun, annotationTrack = c("name","grid"))

plotdefault2 = data.frame(freq = seq(-0.5,0.5, length.out=100),y = as.factor(1))  
p_cbar = ggplot(data = plotdefault2, aes(x=freq,y=y)) +
  geom_tile(aes(fill=freq, alpha=0.5)) + 
  scale_fill_gradientn(colours=c("blue","white","red"), limits=c(-0.5,0.5), breaks=seq(-0.5,0.5,by=0.1)) +
  theme_minimal() +
  theme(legend.title = element_blank(),
        legend.position = "none",
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        axis.text.x=element_blank()) +
  coord_flip()
p_cbar

```

