---
title: "Gene Expression Decoding"
output: html_document
---

# Gene expression decoding analysis

```{r, warning=FALSE, message=FALSE}
easypackages::libraries("here","ggplot2","rjson")

root_dir = "/Users/mlombardo/Dropbox/euaims/data/adir"
code_dir = file.path(root_dir,"adi_subtyping","code")
result_dir = file.path(root_dir,"ns_gex_decode")
asd_genelist_dir = file.path(root_dir,"asd_genelists")

source(file.path(code_dir,"ns_gene_decode.R"))
source(file.path(code_dir,"genelistOverlap.R"))
```

Run the decoding in Neurosynth

```{r, warning=FALSE, message=FALSE}
RUN_DECODING = FALSE
tissue_type = "full"
fdr_thresh = 0.05

if (RUN_DECODING){
  # run gex decoding for each IC map of interest
  img2use = "IC17"
  nv_id = 319463
  fname2save = file.path(result_dir,img2use,sprintf("%s_%s.csv",nv_id,tissue_type))
  ns_gene_decode(image = nv_id, tissue = tissue_type, fname2save = fname2save, fdr_thresh = fdr_thresh)
  
  img2use = "IC04"
  nv_id = 319464
  fname2save = file.path(result_dir,img2use,sprintf("%s_%s.csv",nv_id,tissue_type))
  ns_gene_decode(image = nv_id, tissue = tissue_type, fname2save = fname2save, fdr_thresh = fdr_thresh)
  
  img2use = "IC14"
  nv_id = 319465
  fname2save = file.path(result_dir,img2use,sprintf("%s_%s.csv",nv_id,tissue_type))
  ns_gene_decode(image = nv_id, tissue = tissue_type, fname2save = fname2save, fdr_thresh = fdr_thresh)
  
  img2use = "IC20"
  nv_id = 359783
  fname2save = file.path(result_dir,img2use,sprintf("%s_%s.csv",nv_id,tissue_type))
  ns_gene_decode(image = nv_id, tissue = tissue_type, fname2save = fname2save, fdr_thresh = fdr_thresh)

  img2use = "IC07"
  nv_id = 359784
  fname2save = file.path(result_dir,img2use,sprintf("%s_%s.csv",nv_id,tissue_type))
  ns_gene_decode(image = nv_id, tissue = tissue_type, fname2save = fname2save, fdr_thresh = fdr_thresh)

  img2use = "diff_IC17_IC04"
  nv_id = 358757
  fname2save = file.path(result_dir,img2use,sprintf("%s_%s.csv",nv_id,tissue_type))
  ns_gene_decode(image = nv_id, tissue = tissue_type, fname2save = fname2save, fdr_thresh = fdr_thresh, pval_thresh=0.05)
  
  img2use = "add_IC12_IC17"
  nv_id = 358758
  fname2save = file.path(result_dir,img2use,sprintf("%s_%s.csv",nv_id,tissue_type))
  ns_gene_decode(image = nv_id, tissue = tissue_type, fname2save = fname2save, fdr_thresh = fdr_thresh, pval_thresh=0.05)
  
  img2use = "add_IC04_IC12"
  nv_id = 358759
  fname2save = file.path(result_dir,img2use,sprintf("%s_%s.csv",nv_id,tissue_type))
  ns_gene_decode(image = nv_id, tissue = tissue_type, fname2save = fname2save, fdr_thresh = fdr_thresh, pval_thresh=0.05)
  
  img2use = "diff_comp_map_grp1_grp2"
  nv_id = 358983
  fname2save = file.path(result_dir,img2use,sprintf("%s_%s.csv",nv_id,tissue_type))
  ns_gene_decode(image = nv_id, tissue = tissue_type, fname2save = fname2save, fdr_thresh = fdr_thresh, pval_thresh=0.05)
  
  img2use = "add_IC04_IC14"
  nv_id = 358988
  fname2save = file.path(result_dir,img2use,sprintf("%s_%s.csv",nv_id,tissue_type))
  ns_gene_decode(image = nv_id, tissue = tissue_type, fname2save = fname2save, fdr_thresh = fdr_thresh, pval_thresh=0.05)
 
} # if (RUN_DECODING)

```

Run enrichment tests with gex decoded lists and ASD-relevant gene lists

```{r, warning=FALSE, message=FALSE}
satterstrom_102 = as.character(read.csv(file.path(asd_genelist_dir,"satterstrom_2020_cell_102asdriskgenes.txt"),header = FALSE)$V1)

sfari_genes = as.character(read.csv(file.path(asd_genelist_dir,"sfari_genes_14.01.2020.txt"),header = FALSE)$V1)

asd_demods_down = as.character(read.csv(file.path(asd_genelist_dir,"parikshak_2016_down_de_modules.txt"),header = FALSE)$V1)

asd_demods_up = as.character(read.csv(file.path(asd_genelist_dir,"parikshak_2016_up_de_modules.txt"),header = FALSE)$V1)

excitatory_de_genes = as.character(read.csv(file.path(asd_genelist_dir,"velmeshev_2019_science_L23456degenes.txt"),header = FALSE)$V1)

inhibitory_de_genes = as.character(read.csv(file.path(asd_genelist_dir,"velmeshev_2019_science_INPVSSTVIPSV2Cdegenes.txt"),header = FALSE)$V1)

microglia_de_genes = as.character(read.csv(file.path(asd_genelist_dir,"velmeshev_2019_science_Microgliadegenes.txt"),header = FALSE)$V1)

oligodendrocyte_de_genes = as.character(read.csv(file.path(asd_genelist_dir,"velmeshev_2019_science_Oligodendrocytesdegenes.txt"),header = FALSE)$V1)

astrocyte_de_genes = as.character(read.csv(file.path(asd_genelist_dir,"velmeshev_2019_science_Astrocytedegenes.txt"),header = FALSE)$V1)

endothelial_de_genes = as.character(read.csv(file.path(asd_genelist_dir,"velmeshev_2019_science_Endothelialdegenes.txt"),header = FALSE)$V1)

# kosmicki_2ptv = as.character(read.csv(file.path(asd_genelist_dir,"kosmicki_2dnptv_asdgenes.txt"),header = FALSE)$V1)
# 
# kosmicki_1ptv_pli09 = as.character(read.csv(file.path(asd_genelist_dir,"kosmicki_1dnptv_AND_pli0.9_asdgenes.txt"),header = FALSE)$V1)
#
# chd8_1 = as.character(read.csv(file.path(asd_genelist_dir,"CHD8_brain+hnsc_promoterBinding_Cotney_2014_natcommun.txt"),header = FALSE)$V1)
# 
# chd8_2 = as.character(read.csv(file.path(asd_genelist_dir,"CHD8_targets_Sugathan.txt"),header = FALSE)$V1)
# 
# fmrp_1 = as.character(read.csv(file.path(asd_genelist_dir,"ASDfmrp_interactors_genelist_Darnell_Parikshak.txt"),header = FALSE)$V1)
# 
# fmrp_2 = as.character(read.csv(file.path(asd_genelist_dir,"greenblatt_fmrp_all.txt"),header = FALSE)$V1)
# 
# 
# asd_prenatal_1 = as.character(read.csv(file.path(asd_genelist_dir,"parikshak_2013_M2_M3.txt"),header = FALSE)$V1)
# asd_prenatal_2 = as.character(read.csv(file.path(asd_genelist_dir,"eising_M3_M9_M12.txt"),header = FALSE)$V1)


add_IC04_IC14_genes = as.character(read.csv(file.path(result_dir,"add_IC04_IC14","358988_full_pos_t_fdr0.05.csv"))$symbol)
IC17genes = as.character(read.csv(file.path(result_dir,"IC17","319463_full_pos_t_fdr0.05.csv"))$symbol)
IC14genes = as.character(read.csv(file.path(result_dir,"IC14","319465_full_pos_t_fdr0.05.csv"))$symbol)
IC04genes = as.character(read.csv(file.path(result_dir,"IC04","319464_full_pos_t_fdr0.05.csv"))$symbol)
IC20genes = as.character(read.csv(file.path(result_dir,"IC20","359783_full_pos_t_fdr0.05.csv"))$symbol)


geneclasses = list(satterstrom_102,
                   sfari_genes,
                   asd_demods_down,
                   asd_demods_up,
                   excitatory_de_genes,
                   inhibitory_de_genes,
                   microglia_de_genes,
                   oligodendrocyte_de_genes,
                   astrocyte_de_genes,
                   endothelial_de_genes)

geneclassnames = c("ASD 102 dnPTVs",
                   "SFARI ASD",
                   "ASD CTX Downreg Mods",
                   "ASD CTX Upreg Mods",
                   "Excitatory DE",
                   "Inhibitory DE",
                   "Microglia DE",
                   "Oligodendrocyte DE",
                   "Astrocyte DE",
                   "Endothelial DE")


res_colnames =  c("IC17","IC04","IC14","IC20")
ORmat = data.frame(matrix(nrow = length(geneclasses), 
                          ncol = length(res_colnames)))
logPmat = data.frame(matrix(nrow = length(geneclasses), 
                            ncol = length(res_colnames)))
Pmat = data.frame(matrix(nrow = length(geneclasses), 
                         ncol = length(res_colnames)))
FDRmat = data.frame(matrix(nrow = length(geneclasses), 
                           ncol = length(res_colnames)))
colnames(ORmat) = res_colnames
colnames(logPmat) = res_colnames
colnames(Pmat) = res_colnames
colnames(FDRmat) = res_colnames
rownames(ORmat) = geneclassnames
rownames(logPmat) = geneclassnames
rownames(Pmat) = geneclassnames
rownames(FDRmat) = geneclassnames

backgroundTotal = 20787

for (i in 1:length(geneclasses)){
  # intersect with background list
  genes2 = geneclasses[[i]]
  # mask = is.element(genes2, bglist)
  genes2 = data.frame(genes2)

  # IC17
  overlap_res = genelistOverlap(data.frame(IC17genes),
                                genes2,
                                backgroundTotal,
                                print_result = FALSE,
                                header = FALSE)
  ORmat[i,"IC17"] = overlap_res[[1]]$OR
  logPmat[i,"IC17"] = -log10(overlap_res[[1]]$hypergeo_p)
  Pmat[i,"IC17"] = overlap_res[[1]]$hypergeo_p

  # IC04
  overlap_res = genelistOverlap(data.frame(IC04genes),
                                genes2,
                                backgroundTotal,
                                print_result = FALSE,
                                header = FALSE)
  ORmat[i,"IC04"] = overlap_res[[1]]$OR
  logPmat[i,"IC04"] = -log10(overlap_res[[1]]$hypergeo_p)
  Pmat[i,"IC04"] = overlap_res[[1]]$hypergeo_p
  
  # IC14
  overlap_res = genelistOverlap(data.frame(IC14genes),
                                genes2,
                                backgroundTotal,
                                print_result = FALSE,
                                header = FALSE)
  ORmat[i,"IC14"] = overlap_res[[1]]$OR
  logPmat[i,"IC14"] = -log10(overlap_res[[1]]$hypergeo_p)
  Pmat[i,"IC14"] = overlap_res[[1]]$hypergeo_p
  
  # IC20
  overlap_res = genelistOverlap(data.frame(IC20genes),
                                genes2,
                                backgroundTotal,
                                print_result = FALSE,
                                header = FALSE)
  ORmat[i,"IC20"] = overlap_res[[1]]$OR
  logPmat[i,"IC20"] = -log10(overlap_res[[1]]$hypergeo_p)
  Pmat[i,"IC20"] = overlap_res[[1]]$hypergeo_p
  
} # for (i in 1:length(geneclasses)){

# compute FDR
for (i in 1:dim(Pmat)[2]){
  FDRmat[,i] = p.adjust(Pmat[,i], method = "fdr")
} # for (i in 1:dim(Pmat)[2]){


# make figure
zLIM = c(0,-log10(0.005))
par(mar = c(6, 8.5, 3, 3))
WGCNA::labeledHeatmap(Matrix = logPmat,
                      xLabels = colnames(ORmat),
                      yLabels = rownames(ORmat),
                      ySymbols = NULL,
                      colorLabels = FALSE,
                      colors = WGCNA::blueWhiteRed(50),
                      textMatrix = round(ORmat, digits = 2),
                      setStdMargins = FALSE,
                      cex.text = 1,
                      zlim = zLIM)
```

Overlapping genes for IC17

```{r, warning=FALSE, message=FALSE}
# IC17 - Satterstrom 102
overlap_res = genelistOverlap(data.frame(IC17genes),
                              satterstrom_102,
                              backgroundTotal,
                              print_result = FALSE,
                              header = FALSE)
sort(overlap_res[[1]]$overlapping_genes)

# IC17 - SFARI ASD
overlap_res = genelistOverlap(data.frame(IC17genes),
                              sfari_genes,
                              backgroundTotal,
                              print_result = FALSE,
                              header = FALSE)
sort(overlap_res[[1]]$overlapping_genes)

# IC17 - ASD downreg modules
overlap_res = genelistOverlap(data.frame(IC17genes),
                              asd_demods_down,
                              backgroundTotal,
                              print_result = FALSE,
                              header = FALSE)
write(sort(overlap_res[[1]]$overlapping_genes),file="/Users/mlombardo/Desktop/IC17_downregmod_overlap.txt")
sort(overlap_res[[1]]$overlapping_genes)

# IC17 - ASD Excitatory DE
overlap_res = genelistOverlap(data.frame(IC17genes),
                              excitatory_de_genes,
                              backgroundTotal,
                              print_result = FALSE,
                              header = FALSE)
write(sort(overlap_res[[1]]$overlapping_genes),file="/Users/mlombardo/Desktop/IC17_excitatoryDE_overlap.txt")
sort(overlap_res[[1]]$overlapping_genes)

# IC17 - ASD Inhibitory DE
overlap_res = genelistOverlap(data.frame(IC17genes),
                              inhibitory_de_genes,
                              backgroundTotal,
                              print_result = FALSE,
                              header = FALSE)
sort(overlap_res[[1]]$overlapping_genes)

# IC17 - ASD Astrocyte DE
overlap_res = genelistOverlap(data.frame(IC17genes),
                              astrocyte_de_genes,
                              backgroundTotal,
                              print_result = FALSE,
                              header = FALSE)
sort(overlap_res[[1]]$overlapping_genes)
```

Overlapping genes for IC04

```{r, warning=FALSE, message=FALSE}
# IC04 - Satterstrom 102
overlap_res = genelistOverlap(data.frame(IC04genes),
                              satterstrom_102,
                              backgroundTotal,
                              print_result = FALSE,
                              header = FALSE)
sort(overlap_res[[1]]$overlapping_genes)

# IC04 - SFARI ASD
overlap_res = genelistOverlap(data.frame(IC04genes),
                              sfari_genes,
                              backgroundTotal,
                              print_result = FALSE,
                              header = FALSE)
sort(overlap_res[[1]]$overlapping_genes)

# IC04 - ASD downreg modules
overlap_res = genelistOverlap(data.frame(IC04genes),
                              asd_demods_down,
                              backgroundTotal,
                              print_result = FALSE,
                              header = FALSE)
sort(overlap_res[[1]]$overlapping_genes)

# IC04 - ASD Excitatory DE
overlap_res = genelistOverlap(data.frame(IC04genes),
                              excitatory_de_genes,
                              backgroundTotal,
                              print_result = FALSE,
                              header = FALSE)
write(sort(overlap_res[[1]]$overlapping_genes),file="/Users/mlombardo/Desktop/IC04_excitatoryDE_overlap.txt")
sort(overlap_res[[1]]$overlapping_genes)

# IC04 - ASD Inhibitory DE
overlap_res = genelistOverlap(data.frame(IC04genes),
                              inhibitory_de_genes,
                              backgroundTotal,
                              print_result = FALSE,
                              header = FALSE)
sort(overlap_res[[1]]$overlapping_genes)
```

Overlapping genes for IC14

```{r, warning=FALSE, message=FALSE}
# IC14 - ASD upreg modules
overlap_res = genelistOverlap(data.frame(IC14genes),
                              asd_demods_up,
                              backgroundTotal,
                              print_result = FALSE,
                              header = FALSE)
write(sort(overlap_res[[1]]$overlapping_genes),file="/Users/mlombardo/Desktop/IC14_upregmod_overlap.txt")
sort(overlap_res[[1]]$overlapping_genes)
```