---
title: "procEUAIMS_adi_connectivity_dsm5_NEW_3grpSupervised.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## EU-AIMS ADI-R Subtyping Connectivity Analysis


```{r, warning=FALSE, message=FALSE}
easypackages::libraries(c("here","ggplot2","nlme","readxl"))
source("/Users/mlombardo/Dropbox/GitHubRepos/utils/cohens_d.R")
source("/Users/mlombardo/Dropbox/R/Repfunctionspack6.R")
source("/Users/mlombardo/Dropbox/R/get_ggColorHue.R")
fdr_thresh = 0.05

rootpath = "/Users/mlombardo/Dropbox/euaims/data/adir"
datapath = here("data")
resultpath = here("results")
plotpath = here("plots")
fname = "partialCorData_ridge_lambda1.3GrpSupervised.txt"

fname2open = file.path(datapath, fname)
df = read.delim(fname2open)
```




```{r, warning=FALSE, message=FALSE}
RUNANALYSIS = TRUE

if (RUNANALYSIS==TRUE) {
  
  # columns with connectivity data
  vars2use = colnames(df)[10:ncol(df)]
  
  cnames = c("compNames","All.fstat","All.pvalue","All.AIC","All.BIC",
             "AllCaseControl.fstat","AllCaseControl.pvalue",
             "AllCaseControl.AIC","AllCaseControl.BIC","AllCaseControl.es",
             "Disc.fstat","Disc.pvalue","Disc.AIC","Disc.BIC",
             "Rep.fstat","Rep.pvalue","Rep.AIC","Rep.BIC",
             "ASD1Disc_vs_TD.tstat","ASD1Disc_vs_TD.pval", 
             "ASD1Disc_vs_TD.es","ASD1Disc_vs_TD.AIC","ASD1Disc_vs_TD.BIC",
             "ASD1Rep_vs_TD.tstat","ASD1Rep_vs_TD.pval","ASD1Rep_vs_TD.es", 
             "ASD1Rep_vs_TD.AIC","ASD1Rep_vs_TD.BIC", "ASD1.repBF",
             "ASD2Disc_vs_TD.tstat","ASD2Disc_vs_TD.pval", 
             "ASD2Disc_vs_TD.es","ASD2Disc_vs_TD.AIC","ASD2Disc_vs_TD.BIC",
             "ASD2Rep_vs_TD.tstat","ASD2Rep_vs_TD.pval","ASD2Rep_vs_TD.es",
             "ASD2Rep_vs_TD.AIC","ASD2Rep_vs_TD.BIC", "ASD2.repBF",
             "ASD3Disc_vs_TD.tstat","ASD3Disc_vs_TD.pval", 
             "ASD3Disc_vs_TD.es","ASD3Disc_vs_TD.AIC","ASD3Disc_vs_TD.BIC",
             "ASD3Rep_vs_TD.tstat","ASD3Rep_vs_TD.pval","ASD3Rep_vs_TD.es", 
             "ASD3Rep_vs_TD.AIC","ASD3Rep_vs_TD.BIC","ASD3.repBF",
             "CaseControlDisc.tstat","CaseControlDisc.pval", 
             "CaseControlDisc.es","CaseControlDisc.AIC","CaseControlDisc.BIC",
             "CaseControlRep.tstat","CaseControlRep.pval","CaseControlRep.es", 
             "CaseControlRep.AIC","CaseControlRep.BIC","CaseControl.repBF")
  
  aovres = data.frame(matrix(nrow = length(vars2use),ncol = length(cnames)))
  colnames(aovres) = cnames
  rownames(aovres) = vars2use
  aovres$compNames = vars2use
  vars2loop = c(1:length(vars2use))
  #vars2loop = c(1:77,79:90,92:length(vars2use))
  #vars2loop = c(246:length(vars2use))
  for (i in vars2loop) {
  	y_var = vars2use[i]
  	
  	# construct linear model
  	
  	# mixed-effect model: site as random factor, all other covariates as fixed factors
  	fx_form = as.formula(sprintf("%s ~ %s + %s + %s  + %s",y_var,"subgrp","sex","scan_age","meanFD"))
  	rx_form = as.formula(sprintf("~ 1|%s","site"))
  	mod2use = eval(substitute(lme(fixed = fx_form, random = rx_form, data = df, na.action = na.omit)))
  
  	# run ANOVA
  	res = anova(mod2use)
  	# extract F-stat and pvalue
  	fstat = res[2,3]
  	pval = res[2,4]
  	aovres[y_var,"All.fstat"] = fstat
  	aovres[y_var,"All.pvalue"] = pval
    aovres[y_var,"All.AIC"] = AIC(mod2use)
    aovres[y_var,"All.BIC"] = BIC(mod2use)
    
    # case-control
    fx_form = as.formula(sprintf("%s ~ %s + %s + %s  + %s",y_var,"Diagnosis","sex","scan_age","meanFD"))
  	mod2use = eval(substitute(lme(fixed = fx_form, random = rx_form, data = df, na.action = na.omit)))
  
  	# run ANOVA
  	res = anova(mod2use)
  	# extract F-stat and pvalue
  	fstat = res[2,3]
  	pval = res[2,4]
  	aovres[y_var,"AllCaseControl.fstat"] = fstat
  	aovres[y_var,"AllCaseControl.pvalue"] = pval
    aovres[y_var,"AllCaseControl.AIC"] = AIC(mod2use)
    aovres[y_var,"AllCaseControl.BIC"] = BIC(mod2use)
    
    # grab residuals after accounting for sex and scan_age
  	fx_form2 = as.formula(sprintf("%s ~ %s + %s  + %s",y_var,"sex","scan_age","meanFD"))
  	mod2use = eval(substitute(lme(fixed = fx_form2, random = rx_form, data = df, na.action = na.omit)))
    df$data2plot = resid(mod2use)
    aovres[y_var,"AllCaseControl.es"] = cohens_d(df$data2plot[df$Diagnosis=="ASD"],
                                           df$data2plot[df$Diagnosis=="TD"])

    
    # run analyses on Discovery and Replication datasets
  	#df_Disc = subset(df, df$dataset=="Discovery")
    #df_Rep = subset(df, df$dataset=="Replication")
  	df_Disc = subset(df, df$dataset=="Replication")
    df_Rep = subset(df, df$dataset=="Discovery")
  	
    fx_form = as.formula(sprintf("%s ~ %s + %s + %s  + %s",y_var,"subgrp","sex","scan_age","meanFD"))
    
    # Discovery
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = df_Disc, 
  	                              na.action = na.omit)))
    # run ANOVA
  	res = anova(mod2use)
  	# extract F-stat and pvalue
  	fstat = res[2,3]
  	pval = res[2,4]
  	aovres[y_var,"Disc.fstat"] = fstat
  	aovres[y_var,"Disc.pvalue"] = pval
  	aovres[y_var,"Disc.AIC"] = AIC(mod2use)
  	aovres[y_var,"Disc.BIC"] = BIC(mod2use)
  	
  	# grab residuals after accounting for sex and scan_age
  	fx_form2 = as.formula(sprintf("%s ~ %s + %s  + %s",y_var,"sex","scan_age","meanFD"))
  	mod2use = eval(substitute(lme(fixed = fx_form2, 
  	                              random = rx_form, 
  	                              data = df_Disc, 
  	                              na.action = na.omit)))
    df_Disc$data2plot = resid(mod2use)
  
    # compute t-stats
    fx_form = as.formula(sprintf("%s ~ %s + %s + %s  + %s",y_var,"subgrp","sex","scan_age","meanFD"))
  	rx_form = as.formula(sprintf("~ 1|%s","site"))
  	
  	DASD1 = subset(df_Disc, df_Disc$subgrp=="ASD1" | df_Disc$subgrp=="TD")
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = DASD1, 
  	                              na.action = na.omit)))
    res = summary(mod2use)
    ASD1_vs_TD_Disc_statistic = res$tTable[2,4]
    ASD1_vs_TD_Disc_p.value = res$tTable[2,5]
    ASD1_vs_TD_Disc.AIC = AIC(mod2use)
    ASD1_vs_TD_Disc.BIC = BIC(mod2use)
    
  	DASD2 = subset(df_Disc, df_Disc$subgrp=="ASD2" | df_Disc$subgrp=="TD")
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = DASD2, 
  	                              na.action = na.omit)))
    res = summary(mod2use)
    ASD2_vs_TD_Disc_statistic = res$tTable[2,4]
    ASD2_vs_TD_Disc_p.value = res$tTable[2,5]
    ASD2_vs_TD_Disc.AIC = AIC(mod2use)
    ASD2_vs_TD_Disc.BIC = BIC(mod2use)

  	DASD3 = subset(df_Disc, df_Disc$subgrp=="ASD3" | df_Disc$subgrp=="TD")
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = DASD3, 
  	                              na.action = na.omit)))
    res = summary(mod2use)
    ASD3_vs_TD_Disc_statistic = res$tTable[2,4]
    ASD3_vs_TD_Disc_p.value = res$tTable[2,5]
    ASD3_vs_TD_Disc.AIC = AIC(mod2use)
    ASD3_vs_TD_Disc.BIC = BIC(mod2use)
    
    # case-control model
    fx_form = as.formula(sprintf("%s ~ %s + %s + %s  + %s",y_var,"Diagnosis","sex","scan_age","meanFD"))
  	rx_form = as.formula(sprintf("~ 1|%s","site"))

    # DCaseControl = subset(df_Disc, df_Disc$Diagnosis=="ASD" | df_Disc$Diagnosis=="TD")
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = df_Disc, 
  	                              na.action = na.omit)))
    res = summary(mod2use)
    CaseControl_Disc_statistic = res$tTable[2,4]
    CaseControl_Disc_p.value = res$tTable[2,5]
    CaseControl_Disc.AIC = AIC(mod2use)
    CaseControl_Disc.BIC = BIC(mod2use)

    
    aovres[y_var,"ASD1Disc_vs_TD.tstat"] = ASD1_vs_TD_Disc_statistic
    aovres[y_var,"ASD1Disc_vs_TD.pval"] = ASD1_vs_TD_Disc_p.value
    aovres[y_var,"ASD1Disc_vs_TD.es"] = cohens_d(df_Disc$data2plot[df_Disc$subgrp=="ASD1"],
                                             df_Disc$data2plot[df_Disc$subgrp=="TD"])
    aovres[y_var,"ASD1Disc_vs_TD.AIC"] = ASD1_vs_TD_Disc.AIC
    aovres[y_var,"ASD1Disc_vs_TD.BIC"] = ASD1_vs_TD_Disc.BIC

    aovres[y_var,"ASD2Disc_vs_TD.tstat"] = ASD2_vs_TD_Disc_statistic
    aovres[y_var,"ASD2Disc_vs_TD.pval"] = ASD2_vs_TD_Disc_p.value
    aovres[y_var,"ASD2Disc_vs_TD.es"] = cohens_d(df_Disc$data2plot[df_Disc$subgrp=="ASD2"],
                                             df_Disc$data2plot[df_Disc$subgrp=="TD"])
    aovres[y_var,"ASD2Disc_vs_TD.AIC"] = ASD2_vs_TD_Disc.AIC
    aovres[y_var,"ASD2Disc_vs_TD.BIC"] = ASD2_vs_TD_Disc.BIC

    aovres[y_var,"ASD3Disc_vs_TD.tstat"] = ASD3_vs_TD_Disc_statistic
    aovres[y_var,"ASD3Disc_vs_TD.pval"] = ASD3_vs_TD_Disc_p.value
    aovres[y_var,"ASD3Disc_vs_TD.es"] = cohens_d(df_Disc$data2plot[df_Disc$subgrp=="ASD3"],
                                             df_Disc$data2plot[df_Disc$subgrp=="TD"])
    aovres[y_var,"ASD3Disc_vs_TD.AIC"] = ASD3_vs_TD_Disc.AIC
    aovres[y_var,"ASD3Disc_vs_TD.BIC"] = ASD3_vs_TD_Disc.BIC

    aovres[y_var,"CaseControlDisc.tstat"] = CaseControl_Disc_statistic
    aovres[y_var,"CaseControlDisc.pval"] = CaseControl_Disc_p.value
    aovres[y_var,"CaseControlDisc.es"] = cohens_d(df_Disc$data2plot[df_Disc$Diagnosis=="ASD"],df_Disc$data2plot[df_Disc$Diagnosis=="TD"])
    aovres[y_var,"CaseControlDisc.AIC"] = CaseControl_Disc.AIC
    aovres[y_var,"CaseControlDisc.BIC"] = CaseControl_Disc.BIC

  
    
    # Replication
    fx_form = as.formula(sprintf("%s ~ %s + %s + %s  + %s",y_var,"subgrp","sex","scan_age","meanFD"))
  	rx_form = as.formula(sprintf("~ 1|%s","site"))
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = df_Rep, 
  	                              na.action = na.omit)))
    # run ANOVA
  	res = anova(mod2use)
  	# extract F-stat and pvalue
  	fstat = res[2,3]
  	pval = res[2,4]
  	aovres[y_var,"Rep.fstat"] = fstat
  	aovres[y_var,"Rep.pvalue"] = pval
  	aovres[y_var,"Rep.AIC"] = AIC(mod2use)
  	aovres[y_var,"Rep.BIC"] = BIC(mod2use)
  	
  	# grab residuals after accounting for sex and scan_age
  	fx_form2 = as.formula(sprintf("%s ~ %s + %s  + %s",y_var,"sex","scan_age","meanFD"))
  	mod2use = eval(substitute(lme(fixed = fx_form2, 
  	                              random = rx_form, 
  	                              data = df_Rep, 
  	                              na.action = na.omit)))
    df_Rep$data2plot = resid(mod2use)

    
    # compute t-stats
    fx_form = as.formula(sprintf("%s ~ %s + %s + %s  + %s",y_var,"subgrp","sex","scan_age","meanFD"))
  	rx_form = as.formula(sprintf("~ 1|%s","site"))
  	
  	DASD1 = subset(df_Rep, df_Rep$subgrp=="ASD1" | df_Rep$subgrp=="TD")
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = DASD1, 
  	                              na.action = na.omit)))
    res = summary(mod2use)
    ASD1_vs_TD_Rep_statistic = res$tTable[2,4]
    ASD1_vs_TD_Rep_p.value = res$tTable[2,5]
    ASD1_vs_TD_Rep.AIC = AIC(mod2use)
    ASD1_vs_TD_Rep.BIC = BIC(mod2use)

  	DASD2 = subset(df_Rep, df_Rep$subgrp=="ASD2" | df_Rep$subgrp=="TD")
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = DASD2, 
  	                              na.action = na.omit)))
    res = summary(mod2use)
    ASD2_vs_TD_Rep_statistic = res$tTable[2,4]
    ASD2_vs_TD_Rep_p.value = res$tTable[2,5]
    ASD2_vs_TD_Rep.AIC = AIC(mod2use)
    ASD2_vs_TD_Rep.BIC = BIC(mod2use)

  	DASD3 = subset(df_Rep, df_Rep$subgrp=="ASD3" | df_Rep$subgrp=="TD")
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = DASD3, 
  	                              na.action = na.omit)))
    res = summary(mod2use)
    ASD3_vs_TD_Rep_statistic = res$tTable[2,4]
    ASD3_vs_TD_Rep_p.value = res$tTable[2,5]
    ASD3_vs_TD_Rep.AIC = AIC(mod2use)
    ASD3_vs_TD_Rep.BIC = BIC(mod2use)

    # case-control model
    fx_form = as.formula(sprintf("%s ~ %s + %s + %s  + %s",y_var,"Diagnosis","sex","scan_age","meanFD"))
  	rx_form = as.formula(sprintf("~ 1|%s","site"))

    # DCaseControl = subset(df_Rep, df_Rep$Diagnosis=="ASD" | df_Rep$Diagnosis=="TD")
  	mod2use = eval(substitute(lme(fixed = fx_form, 
  	                              random = rx_form, 
  	                              data = df_Rep, 
  	                              na.action = na.omit)))
    res = summary(mod2use)
    CaseControl_Rep_statistic = res$tTable[2,4]
    CaseControl_Rep_p.value = res$tTable[2,5]
    CaseControl_Rep.AIC = AIC(mod2use)
    CaseControl_Rep.BIC = BIC(mod2use)

    
    aovres[y_var,"ASD1Rep_vs_TD.tstat"] = ASD1_vs_TD_Rep_statistic
    aovres[y_var,"ASD1Rep_vs_TD.pval"] = ASD1_vs_TD_Rep_p.value
    aovres[y_var,"ASD1Rep_vs_TD.es"] = cohens_d(df_Rep$data2plot[df_Rep$subgrp=="ASD1"],
                                            df_Rep$data2plot[df_Rep$subgrp=="TD"])
    aovres[y_var,"ASD1Rep_vs_TD.AIC"] = ASD1_vs_TD_Rep.AIC
    aovres[y_var,"ASD1Rep_vs_TD.BIC"] = ASD1_vs_TD_Rep.BIC

    aovres[y_var,"ASD2Rep_vs_TD.tstat"] = ASD2_vs_TD_Rep_statistic
    aovres[y_var,"ASD2Rep_vs_TD.pval"] = ASD2_vs_TD_Rep_p.value
    aovres[y_var,"ASD2Rep_vs_TD.es"] = cohens_d(df_Rep$data2plot[df_Rep$subgrp=="ASD2"],
                                            df_Rep$data2plot[df_Rep$subgrp=="TD"])
    aovres[y_var,"ASD2Rep_vs_TD.AIC"] = ASD2_vs_TD_Rep.AIC
    aovres[y_var,"ASD2Rep_vs_TD.BIC"] = ASD2_vs_TD_Rep.BIC

    aovres[y_var,"ASD3Rep_vs_TD.tstat"] = ASD3_vs_TD_Rep_statistic
    aovres[y_var,"ASD3Rep_vs_TD.pval"] = ASD3_vs_TD_Rep_p.value
    aovres[y_var,"ASD3Rep_vs_TD.es"] = cohens_d(df_Rep$data2plot[df_Rep$subgrp=="ASD3"],
                                            df_Rep$data2plot[df_Rep$subgrp=="TD"])
    aovres[y_var,"ASD3Rep_vs_TD.AIC"] = ASD3_vs_TD_Rep.AIC
    aovres[y_var,"ASD3Rep_vs_TD.BIC"] = ASD3_vs_TD_Rep.BIC

    aovres[y_var,"CaseControlRep.tstat"] = CaseControl_Rep_statistic
    aovres[y_var,"CaseControlRep.pval"] = CaseControl_Rep_p.value
    aovres[y_var,"CaseControlRep.es"] = cohens_d(df_Rep$data2plot[df_Rep$Diagnosis=="ASD"],df_Rep$data2plot[df_Rep$Diagnosis=="TD"])
    aovres[y_var,"CaseControlRep.AIC"] = CaseControl_Rep.AIC
    aovres[y_var,"CaseControlRep.BIC"] = CaseControl_Rep.BIC

    current_state = sprintf("Loop %d",i)
    fname2save = file.path(resultpath,"anova_allconnections","monitor.csv")
  write.table(current_state, file = fname2save, sep = ",", quote = FALSE, col.names = NA)
  
  
    # print(i)
    # print(y_var)
    # print("ASD1")
    res_bf = BFSALL(tobs = ASD1_vs_TD_Disc_statistic, 
                      trep = ASD1_vs_TD_Rep_statistic, 
                      n1 = sum(df_Disc$subgrp=="ASD1"), 
                      n2 = sum(df_Rep$subgrp=="ASD1"),
                      m1 = sum(df_Disc$subgrp=="TD"), 
                      m2 = sum(df_Rep$subgrp=="TD"),
                      sample = 2, 
                      Type = 'ALL')
    aovres[y_var,"ASD1.repBF"] = res_bf[4,2]
  
    # print("ASD2")
    res_bf = BFSALL(tobs = ASD2_vs_TD_Disc_statistic, 
                    trep = ASD2_vs_TD_Rep_statistic,
                    n1 = sum(df_Disc$subgrp=="ASD2"), 
                    n2 = sum(df_Rep$subgrp=="ASD2"),
                    m1 = sum(df_Disc$subgrp=="TD"), 
                    m2 = sum(df_Rep$subgrp=="TD"),
                    sample = 2, 
                    Type = 'ALL')
    aovres[y_var,"ASD2.repBF"] = res_bf[4,2]
  
    # print("ASD3")
    res_bf = BFSALL(tobs = ASD3_vs_TD_Disc_statistic, 
                    trep = ASD3_vs_TD_Rep_statistic, 
                    n1 = sum(df_Disc$subgrp=="ASD3"), 
                    n2 = sum(df_Rep$subgrp=="ASD3"),
                    m1 = sum(df_Disc$subgrp=="TD"), 
                    m2 = sum(df_Rep$subgrp=="TD"),
                    sample = 2,
                    Type = 'ALL')
    aovres[y_var,"ASD3.repBF"] = res_bf[4,2]
    
    # print("CaseControl")
    res_bf = BFSALL(tobs = CaseControl_Disc_statistic, 
                    trep = CaseControl_Rep_statistic,
                    n1 = sum(df_Disc$Diagnosis=="ASD"), 
                    n2 = sum(df_Rep$Diagnosis=="ASD"),
                    m1 = sum(df_Disc$Diagnosis=="TD"), 
                    m2 = sum(df_Rep$Diagnosis=="TD"),
                    sample = 2, 
                    Type = 'ALL')
    aovres[y_var,"CaseControl.repBF"] = res_bf[4,2]
  
    # save results to a file
    fname2save = file.path(resultpath,"anova_allconnections","partialCor_ALLsubs_ridge1_lme_fx_subgrp_sex_scan_age_rx_site_3grpSupervised.csv")
    write.table(aovres, file = fname2save, sep = ",", quote = FALSE, col.names = NA)

  }
  
  aovres$All.fdr_q = p.adjust(aovres$All.pvalue,method = "fdr")
  aovres$Disc.fdr_q = p.adjust(aovres$Disc.pvalue,method = "fdr")
  aovres$Rep.fdr_q = p.adjust(aovres$Rep.pvalue,method = "fdr")
  # mask1 = aovres$Disc_fdr_q<fdr_thresh
  # mask2 = aovres$Rep_fdr_q<fdr_thresh
  #print(aovres[mask1 & mask2,])
  #print(aovres[aovres$All.fdr_q<fdr_thresh,])
  mask1 = aovres$ASD1.repBF>=10
  mask2 = aovres$ASD2.repBF>=10
  mask3 = aovres$ASD3.repBF>=10
  mask_allBF = mask1 | mask2 | mask3
  print(aovres[mask_allBF,])
  
  # save results to a file
  fname2save = file.path(resultpath,"anova_allconnections","partialCor_ALLsubs_ridge1_lme_fx_subgrp_sex_scan_age_rx_site_3grpSupervised.csv")
  write.table(aovres, file = fname2save, sep = ",", quote = FALSE, col.names = NA)

} else {
  
  fname = file.path(resultpath,"anova_allconnections","partialCor_ALLsubs_ridge1_lme_fx_subgrp_sex_scan_age_rx_site.xlsx")
  aovres = read_excel(fname)
}

mask1 = aovres$ASD1.repBF>=10
mask2 = aovres$ASD2.repBF>=10
mask3 = aovres$ASD3.repBF>=10
mask7 = aovres$All.fdr_q<=0.05
mask8 = aovres$CaseControl.repBF>=10
mask_allBF = mask1 | mask2 | mask3 | mask7 | mask8

aovres[mask_allBF,c("compNames","ASD1.repBF","ASD2.repBF","ASD3.repBF","All.fdr_q","CaseControl.repBF")]
```

## plot significant connections

```{r, warning=FALSE, message=FALSE}
#aovres$compName = rownames(aovres)
dotSize = 2
mask1 = aovres$ASD1.repBF>=10
mask2 = aovres$ASD2.repBF>=10
mask3 = aovres$ASD3.repBF>=10
mask7 = aovres$All.fdr_q<=0.05
mask8 = aovres$CaseControl.repBF>=10
mask_allBF = mask1 | mask2 | mask3 | mask7 | mask8
sig_conn = aovres$compNames[mask_allBF]
sig_df = df[,c(colnames(df)[1:9], sig_conn)]
# sig_df$SCsubgrp = "TD"
# #sig_df$SCsubgrp[is.element(sig_df$subgrp,c("ASD1","ASD2","ASD3"))] = "HighSC"
# #sig_df$SCsubgrp[is.element(sig_df$subgrp,c("ASD4","ASD5"))] = "MidSC"
# #sig_df$SCsubgrp[is.element(sig_df$subgrp,c("ASD6"))] = "MildSC"
# sig_df$SCsubgrp[is.element(sig_df$subgrp,c("ASD1","ASD2","ASD3"))] = "HighSC"
# sig_df$SCsubgrp[is.element(sig_df$subgrp,c("ASD4","ASD5","ASD6"))] = "LowSC"
# #sig_df$SCsubgrp[is.element(sig_df$subgrp,c("ASD6"))] = "MildSC"
# 
# sig_df$SCoverRRBsubgrp = NA
# sig_df$SCoverRRBsubgrp[is.element(sig_df$subgrp,c("TD"))] = "TD"
# sig_df$SCoverRRBsubgrp[is.element(sig_df$subgrp,c("ASD2","ASD3","ASD5"))] = "SCoverRRB"
# sig_df$SCoverRRBsubgrp[is.element(sig_df$subgrp,c("ASD1","ASD4","ASD6"))] = "SCequalRRB"

sig_df_Disc = subset(sig_df, sig_df$dataset=="Discovery")
sig_df_Rep = subset(sig_df, sig_df$dataset=="Replication")


c2use = get_ggColorHue(3)
colors2use = c(c2use,"gray")

for (i in 1:length(sig_conn)) {
  y_var = sig_conn[i]

  # mixed-effect model: site as random factor, all other covariates as fixed factors
	fx_form = as.formula(sprintf("%s ~ %s + %s + %s",y_var,"sex","scan_age","meanFD"))
	rx_form = as.formula(sprintf("~ 1|%s","site"))
	mod2use = eval(substitute(lme(fixed = fx_form, random = rx_form, data = sig_df, na.action = na.omit)))
  	
  # grab residuals after accounting for sex and scan_age
	#lm_formula = as.formula(sprintf("%s ~ %s + %s  + %s + %s",y_var,"site","sex","scan_age","meanFD"))
	#mod2use = eval(substitute(lm(formula = lm_formula, data = sig_df, na.action = na.omit)))
  sig_df$data2plot = resid(mod2use)
  
  # plot all subgrps separately
  p = ggplot(data = sig_df, aes_string(x = "subgrp", y = "data2plot", colour = "subgrp"))
  p = p + geom_jitter(size = dotSize) + geom_boxplot(fill = NA, colour = "#000000", outlier.shape = NA) 
  p = p + xlab("Group") + ylab("Connectivity") + labs(y_var) + scale_colour_manual(values = colors2use)
  ggsave(filename = file.path(plotpath,"DSM5",sprintf("%s_ALL.pdf",y_var)))
  p

  
  # # plot by SC groupings
  # p = ggplot(data = sig_df, aes_string(x = "SCsubgrp", y = "data2plot", colour = "subgrp"))
  # p = p + geom_jitter(size = dotSize) + geom_boxplot(fill = NA, colour = "#000000", outlier.shape = NA) 
  # p = p + xlab("Group") + ylab("Connectivity") + labs(y_var) + scale_colour_manual(values = colors2use)
  # ggsave(filename = file.path(plotpath,"DSM5",sprintf("%s_ALL_SCsubgrps.pdf",y_var)))
  # p

  
  # plot by Dx groupings
  p = ggplot(data = sig_df, aes_string(x = "Diagnosis", y = "data2plot", colour = "subgrp"))
  p = p + geom_jitter(size = dotSize) + geom_boxplot(fill = NA, colour = "#000000", outlier.shape = NA) 
  p = p + xlab("Group") + ylab("Connectivity") + labs(y_var) + scale_colour_manual(values = colors2use)
  ggsave(filename = file.path(plotpath,"DSM5",sprintf("%s_ALL_Dx_SCsubgrps.pdf",y_var)))
  p
  

  
  # mixed-effect model: site as random factor, all other covariates as fixed factors
	fx_form = as.formula(sprintf("%s ~ %s + %s + %s",y_var,"sex","scan_age","meanFD"))
	rx_form = as.formula(sprintf("~ 1|%s","site"))
	mod2use = eval(substitute(lme(fixed = fx_form, random = rx_form, data = sig_df_Disc, na.action = na.omit)))
	
  # grab residuals after accounting for sex and scan_age
	#lm_formula = as.formula(sprintf("%s ~ %s + %s  + %s + %s",y_var,"site","sex","scan_age","meanFD"))
	#mod2use = eval(substitute(lm(formula = lm_formula, data = sig_df_Disc, na.action = na.omit)))
  sig_df_Disc$data2plot = resid(mod2use)


  # mixed-effect model: site as random factor, all other covariates as fixed factors
	fx_form = as.formula(sprintf("%s ~ %s + %s + %s",y_var,"sex","scan_age","meanFD"))
	rx_form = as.formula(sprintf("~ 1|%s","site"))
	mod2use = eval(substitute(lme(fixed = fx_form, random = rx_form, data = sig_df_Rep, na.action = na.omit)))
  
  # grab residuals after accounting for sex and scan_age
	#lm_formula = as.formula(sprintf("%s ~ %s + %s  + %s + %s",y_var,"site","sex","scan_age","meanFD"))
	#mod2use = eval(substitute(lm(formula = lm_formula, data = sig_df_Rep, na.action = na.omit)))
  sig_df_Rep$data2plot = resid(mod2use)
  
 
  df2plot = rbind(sig_df_Disc,sig_df_Rep)

  p = ggplot(data = df2plot, aes_string(x = "subgrp", y = "data2plot", colour = "subgrp")) + facet_grid(. ~ dataset)
  p = p + geom_jitter(size = dotSize) + geom_boxplot(fill = NA, colour = "#000000", outlier.shape = NA) 
  p = p + xlab("Group") + ylab("Connectivity") + labs(y_var) + scale_colour_manual(values = colors2use)
  ggsave(filename = file.path(plotpath,"DSM5",sprintf("%s_DiscRep_covAdj.pdf",y_var)))
  p

  p = ggplot(data = df2plot, aes_string(x = "subgrp", y = y_var, colour = "subgrp")) + facet_grid(. ~ dataset)
  p = p + geom_jitter(size = dotSize) + geom_boxplot(fill = NA, colour = "#000000", outlier.shape = NA) 
  p = p + xlab("Group") + ylab("Connectivity") + labs(y_var) + scale_colour_manual(values = colors2use)
  ggsave(filename = file.path(plotpath,"DSM5",sprintf("%s_DiscRep.pdf",y_var)))
  p
  

}

```

<!-- ``` {r} -->
<!-- # tests on SC>RRB subtypes vs TD for IC24 vs IC28 ----------------------------- -->

<!-- # effect sizes -->
<!-- d_Disc = cohens_d(sig_df_Disc$IC24_IC28[sig_df_Disc$SCoverRRBsubgrp=="SCoverRRB"],sig_df_Disc$IC24_IC28[sig_df_Disc$SCoverRRBsubgrp=="TD"]) -->
<!-- d_Rep = cohens_d(sig_df_Rep$IC24_IC28[sig_df_Rep$SCoverRRBsubgrp=="SCoverRRB"],sig_df_Rep$IC24_IC28[sig_df_Rep$SCoverRRBsubgrp=="TD"]) -->

<!-- # t-stats -->
<!-- tDisc = t.test(sig_df_Disc$IC24_IC28[sig_df_Disc$SCoverRRBsubgrp=="SCoverRRB"],sig_df_Disc$IC24_IC28[sig_df_Disc$SCoverRRBsubgrp=="TD"]) -->
<!-- tRep = t.test(sig_df_Rep$IC24_IC28[sig_df_Rep$SCoverRRBsubgrp=="SCoverRRB"],sig_df_Rep$IC24_IC28[sig_df_Rep$SCoverRRBsubgrp=="TD"]) -->

<!-- # Replication Bayes Factor -->
<!-- rBF=BFSALL(tobs = tDisc$statistic, -->
<!--            trep=tRep$statistic,  -->
<!--            n1 = sum(sig_df_Disc$SCoverRRBsubgrp=="SCoverRRB"),  -->
<!--            n2=sum(sig_df_Rep$SCoverRRBsubgrp=="SCoverRRB"),  -->
<!--            m1 = sum(sig_df_Disc$SCoverRRBsubgrp=="TD"),  -->
<!--            m2 = sum(sig_df_Rep$SCoverRRBsubgrp=="TD"),  -->
<!--            sample=2,  -->
<!--            Type='ALL') -->

<!-- print("Discovery t-test SC>RRB vs TD") -->
<!-- tDisc -->
<!-- print(sprintf("Cohens d = %f",d_Disc)) -->
<!-- print("Replication t-test SC>RRB vs TD") -->
<!-- tRep -->
<!-- print(sprintf("Cohens d = %f",d_Rep)) -->
<!-- print("Replication Bayes Factor") -->
<!-- rBF -->

<!-- ``` -->


<!-- ``` {r} -->
<!-- # tests on SC=RRB subtypes vs TD for IC24 vs IC28 ----------------------------- -->

<!-- # effect sizes -->
<!-- d_Disc = cohens_d(sig_df_Disc$IC24_IC28[sig_df_Disc$SCoverRRBsubgrp=="SCequalRRB"],sig_df_Disc$IC24_IC28[sig_df_Disc$SCoverRRBsubgrp=="TD"]) -->
<!-- d_Rep = cohens_d(sig_df_Rep$IC24_IC28[sig_df_Rep$SCoverRRBsubgrp=="SCequalRRB"],sig_df_Rep$IC24_IC28[sig_df_Rep$SCoverRRBsubgrp=="TD"]) -->

<!-- # t-stats -->
<!-- tDisc = t.test(sig_df_Disc$IC24_IC28[sig_df_Disc$SCoverRRBsubgrp=="SCequalRRB"],sig_df_Disc$IC24_IC28[sig_df_Disc$SCoverRRBsubgrp=="TD"]) -->
<!-- tRep = t.test(sig_df_Rep$IC24_IC28[sig_df_Rep$SCoverRRBsubgrp=="SCequalRRB"],sig_df_Rep$IC24_IC28[sig_df_Rep$SCoverRRBsubgrp=="TD"]) -->

<!-- # Replication Bayes Factor -->
<!-- rBF=BFSALL(tobs = tDisc$statistic, -->
<!--            trep=tRep$statistic,  -->
<!--            n1 = sum(sig_df_Disc$SCoverRRBsubgrp=="SCequalRRB"),  -->
<!--            n2=sum(sig_df_Rep$SCoverRRBsubgrp=="SCequalRRB"),  -->
<!--            m1 = sum(sig_df_Disc$SCoverRRBsubgrp=="TD"),  -->
<!--            m2 = sum(sig_df_Rep$SCoverRRBsubgrp=="TD"),  -->
<!--            sample=2,  -->
<!--            Type='ALL') -->

<!-- print("Discovery t-test SC=RRB vs TD") -->
<!-- tDisc -->
<!-- print(sprintf("Cohens d = %f",d_Disc)) -->
<!-- print("Replication t-test SC-RRB vs TD") -->
<!-- tRep -->
<!-- print(sprintf("Cohens d = %f",d_Rep)) -->
<!-- print("Replication Bayes Factor") -->
<!-- rBF -->

<!-- ``` -->